##===========================================================
# This inluces all of the router of web link with http protocol
##===========================================================

from django.urls import include, path
from django.conf.urls import url
from backend import views

urlpatterns = [  
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('request_listings/', views.request_listings, name='request_listings'),
    path('favourite/', views.favourite, name='favourite'),
    path('undo/', views.undo, name='undo'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('listing/', views.listing, name='listing'),
    path('posting/', views.posting, name='posting'),
    path('upload_photo/', views.upload_photo, name='upload_photo'),
    path('delete_photo/', views.delete_photo, name='delete_photo'),
    path('upload_review_photo/', views.upload_review_photo, name='upload_review_photo'),
    path('delete_review_photo/', views.delete_review_photo, name='delete_review_photo'),
    path('user_requests/', views.user_requests, name='user_requests'),
    path('user_request_active/', views.user_active_request, name='user_active_request'),
    path('user_request_pending/', views.user_pending_request, name='user_pending_request'),
    path('user_request_active/archive_request/', views.archiveRequest, name='archiveRequest'),
    path('user_request_pending/archive_request/', views.archiveRequest, name='archiveRequest'),
    path('user_requests/archive_request/', views.archiveRequest, name='archiveRequest'),
    path('user_request_active/public_request/', views.publicRequest, name='publicRequest'),
    path('user_request_pending/public_request/', views.publicRequest, name='publicRequest'),
    path('user_requests/public_request/', views.publicRequest, name='publicRequest'),
    path('request_single/', views.request_single, name='request_single'),
    path('request/', views.request, name='request'),
    path('search_requests/', views.search_requests, name='search_requests'),
    path('update_data/', views.updata_data, name='update data'),
    path('listing_single/', views.listing_single, name='listing_single'),
    path('reservation/<int:accommodation_id>', views.reservation, name='reservation'),
    path('confirm_reservation/<int:accommodation_id>', views.confirm_reservation, name='confirm_reservation'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('upload_user_protrait/', views.upload_user_protrait, name='upload_user_protrait'),
    path('user_listings/', views.user_listings, name='user_listings'),
    path('user_listings_active/', views.user_active_listings, name='user_active_listings'),
    path('user_listings_pending/', views.user_pending_listings, name='user_pending_listings'),
    path('change_password/', views.changePwd, name='changePwd'),
    path('user_listings_active/archive_listing/', views.archiveListing, name='archiveListing'),
    path('user_listings_pending/archive_listing/', views.archiveListing, name='archiveListing'),
    path('user_listings/archive_listing/', views.archiveListing, name='archiveListing'),
    path('user_listings_active/public_listing/', views.publicListing, name='publicListing'),
    path('user_listings_pending/public_listing/', views.publicListing, name='publicListing'),
    path('user_listings/public_listing/', views.publicListing, name='publicListing'),
    path('reviews_for_host/', views.reviews_for_host, name='reviews_for_host'),
    path('user_reviews/', views.user_reviews, name='user_reviews'),
    path('booking_history/', views.booking_history, name='booking_history'),
    path('cancel_order/', views.cancel_order, name='cancel_order'),
    path('refund_order/', views.refund_order, name='refund_order'),
    path('reply_to_review/', views.reply_to_review, name='reply_to_review'),
    path('reply_to_reply/', views.reply_to_reply, name='reply_to_reply'),
    path('add_reviews/<int:acc_id>', views.add_reviews, name='add_reviews'),
    path('add_feedbacks/<int:request_id>', views.add_feedbacks, name='add_feedbacks'),
    path('reply_to_feedbacks/', views.reply_to_feedbacks, name='reply_to_feedbacks'),
    path('reply_reply_request/', views.reply_reply_request, name='reply_reply_request'),
]
